"use client";

import { useState } from "react";
import { MonthYearPicker } from "@/components/shared/MonthYearPicker";
import { Download, Loader2 } from "lucide-react";
import { toast } from "sonner";
import api from "@/lib/axios";

export function MonthlyReportDownload() {
  const now = new Date();
  const [year, setYear] = useState(now.getFullYear());
  const [month, setMonth] = useState(now.getMonth() + 1);
  const [loading, setLoading] = useState(false);

  const handleDownload = async () => {
    setLoading(true);
    try {
      const data = await api.get(`/reports/monthly?year=${year}&month=${month}`).then(r => r.data);

      // Build a simple text-based report
      const lines = [
        `========================================`,
        `   MESS MANAGEMENT SYSTEM — MONTHLY REPORT`,
        `   ${new Date(year, month - 1).toLocaleString("default", { month: "long" })} ${year}`,
        `   Generated: ${new Date().toLocaleDateString()}`,
        `========================================`,
        ``,
        `SUMMARY`,
        `------`,
        `Total Meals: ${data.totalMeals}`,
        `Total Bazar Cost: BDT ${data.totalBazarCost}`,
        `Meal Rate: BDT ${data.mealRate}`,
        `Fund Collected: BDT ${data.totalFundCollected}`,
        `Fund Withdrawn: BDT ${data.totalFundWithdrawn}`,
        `Current Balance: BDT ${data.currentBalance}`,
        ``,
        `MEAL DETAILS`,
        `------------`,
        ``,
      ];

      // Group meals by member
      const mealsByMember = new Map<string, { name: string; meals: any[] }>();
      for (const meal of data.meals) {
        const existing = mealsByMember.get(meal.memberId);
        if (existing) {
          existing.meals.push(meal);
        } else {
          mealsByMember.set(meal.memberId, { name: meal.member.name, meals: [meal] });
        }
      }

      for (const [_, member] of mealsByMember) {
        lines.push(`${member.name}: ${member.meals.reduce((s: number, m: any) => s + m.mealCount, 0)} meals`);
      }

      lines.push(``);
      lines.push(`BAZAR ENTRIES`);
      lines.push(`-------------`);
      for (const b of data.bazarEntries) {
        lines.push(`${b.date.split("T")[0]} | ${b.member.name} | BDT ${b.amount} | ${b.description || "-"}`);
      }

      lines.push(``);
      lines.push(`TRANSACTIONS`);
      lines.push(`------------`);
      for (const t of data.transactions) {
        lines.push(`${t.date.split("T")[0]} | ${t.member.name} | ${t.type} | BDT ${t.amount} | ${t.description || "-"}`);
      }

      lines.push(``);
      lines.push(`CLEANING LOGS`);
      lines.push(`-------------`);
      for (const c of data.cleaningLogs) {
        lines.push(`${c.date.split("T")[0]} | ${c.type} | ${c.member.name}`);
      }

      lines.push(``);
      lines.push(`Generated by MessBoard System`);
      lines.push(`Timestamp: ${new Date().toISOString()}`);

      const blob = new Blob([lines.join("\n")], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `mess-report-${year}-${String(month).padStart(2, "0")}.txt`;
      a.click();
      URL.revokeObjectURL(url);

      toast.success("Report downloaded!");
    } catch (err: any) {
      toast.error(err.message || "Failed to generate report");
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="mms-section-title">Monthly Reports</h1>
          <p className="mms-section-subtitle">Download monthly summary as PDF or text</p>
        </div>
        <MonthYearPicker year={year} month={month} onChange={(y, m) => { setYear(y); setMonth(m); }} />
      </div>

      <div className="mms-card">
        <h3 className="font-semibold text-[hsl(var(--mms-text-primary))] mb-2">
          Download Report for {new Date(year, month - 1).toLocaleString("default", { month: "long" })} {year}
        </h3>
        <p className="text-sm text-[hsl(var(--mms-text-muted))] mb-4">
          Generates a text-based report with meals, bazar entries, transactions, and cleaning logs.
        </p>
        <button
          onClick={handleDownload}
          disabled={loading}
          className="px-4 py-2.5 bg-[hsl(var(--mms-brand-primary))] text-white text-sm font-medium rounded-[var(--mms-radius-md)] hover:bg-[hsl(var(--mms-brand-primary-dark))] transition-colors disabled:opacity-50 flex items-center gap-2"
        >
          {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
          Download Report
        </button>
      </div>
    </>
  );
}
